name: Atualização do ambiente de homologação com rebase
on:
  push:
    branches:
      - main
jobs:
  atualizacao_homologation:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2
        with:
          ref: homologation
      - name: Atualizar o ambiente de homologação com as alterações de produção
        run: |
          git fetch origin main
          git rebase origin/main
        working-directory: .
      - name: Realizar commit e push das alterações no ambiente de homologação
        uses: EndBug/add-and-commit@v7
        with:
          message: "Atualização do ambiente de homologação com as alterações de produção"
          author_name: "Github Actions"
          author_email: "actions@github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
